# -*- coding: utf-8 -*-
"""ETL 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_fDO6-Lm9JafwAa3d4bJ4qSh3fubgOg
"""

!pip install pymongo

import pandas as pd
from pymongo import MongoClient

# --- ETL para penguins_size.csv ---

# Extract

def extract_data(filepath):
    print("Extrayendo datos...")
    try:
        df = pd.read_csv(filepath)
        print("Datos extraídos exitosamente.")
        return df
    except Exception as e:
        print(f"Error en la extracción de datos: {e}")
        return None

# Transform

def transform_data(df):
    print("Transformando datos...")

    # Limpieza: eliminar filas completamente vacías o con valores críticos nulos
    df = df.dropna(subset=['culmen_length_mm', 'culmen_depth_mm', 'flipper_length_mm', 'body_mass_g']).copy()

    # Conversión de unidades
    df.loc[:, 'culmen_length_in'] = df['culmen_length_mm'] * 0.0393701
    df.loc[:, 'culmen_depth_in'] = df['culmen_depth_mm'] * 0.0393701
    df.loc[:, 'flipper_length_in'] = df['flipper_length_mm'] * 0.0393701
    df.loc[:, 'body_mass_lb'] = df['body_mass_g'] * 0.00220462

    # Normalizar nombres
    df.loc[:, 'species'] = df['species'].str.title()
    df.loc[:, 'sex'] = df['sex'].str.upper()

    print("Transformación completa. Vista previa de los datos:")
    print(df.head())

    return df

# Load to CSV

def load_data(df, output_path):
    print(f"Cargando datos en {output_path}...")
    try:
        df.to_csv(output_path, index=False)
        print("Datos cargados exitosamente.")
    except Exception as e:
        print(f"Error al guardar los datos: {e}")

# Load to MongoDB Atlas

def load_to_mongo(df, uri):
    print("Cargando datos a MongoDB Atlas...")
    try:
        client = MongoClient(uri)
        db = client['Pinguinos']
        collection = db['ETL']

        records = json.loads(df.to_json(orient='records'))
        collection.insert_many(records)
        print("Datos insertados exitosamente en MongoDB Atlas.")
    except Exception as e:
        print(f"Error al insertar en MongoDB: {e}")

# --- Ejecutar ETL ---

if __name__ == "__main__":
    input_path = "/content/penguins_size.csv"
    output_path = "penguins_etl_output.csv"

    # URI de MongoDB Atlas
    MONGO_URI = "mongodb+srv://Michel:D1033683896@cluster0.0lict.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

    data = extract_data(input_path)
    if data is not None:
        transformed = transform_data(data)
        load_data(transformed, output_path)

        print("\nDescargando archivo transformado...")
        files.download(output_path)

        load_to_mongo(transformed, MONGO_URI)